# Offense count: 46
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: aligned, indented, indented_relative_to_receiver
Layout/MultilineMethodCallIndentation:
  Enabled: false

# Offense count: 18
Metrics/AbcSize:
  Max: 41

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 82
  Exclude:
    - 'lib/capistrano/**/*.rake'

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 113

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 11

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 124

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 54
Style/Documentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'flair_bot.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'baseballbot/off_day.rb'
    - 'baseballbot/pregames.rb'
    - 'check_messages.rb'
    - 'mod_queue_slack.rb'
