require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

#
# Coding Style
#

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/EmptyMethod:
  EnforcedStyle: expanded

#
# Disabled Cops
#

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

# New Cops

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
