require:
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

#
# Coding Style
#

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/EmptyMethod:
  EnforcedStyle: expanded

# New Cops

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
