inherit_from: ../.rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

# This cop is causing issues with the Ruby LSP
RSpec/AlignLeftLetBrace:
  Enabled: false
